version: '3'

services:
  mariadb-dev:
    image: mariadb:10
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogapp
      MYSQL_USER: vartanbeno
      MYSQL_PASSWORD: password
    volumes:
      - "./data:/var/lib/mysql:rw"
      - "./mariadb_init:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"

  client:
    image: mariadb:10
    container_name: client
    depends_on:
      - mariadb-dev
    command: mysql -uvartanbeno -ppassword -hmariadb-dev blogapp
