version: '3'

services:
  mysql-dev:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blogapp
      MYSQL_USER: vartanbeno
      MYSQL_PASSWORD: password
    volumes:
      - "./data:/var/lib/mysql:rw"
      - "./mysql_init:/docker-entrypoint-initdb.d"
    ports:
      - "3306:3306"

  client:
    image: mysql:8
    container_name: client
    depends_on:
      - mysql-dev
    command: mysql -uvartanbeno -ppassword -hmysql-dev blogapp

  mysql-dev-legacy:
    image: mysql:5
    container_name: db-legacy
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: legacyapp
    ports:
      - "3308:3306"

  client-legacy:
    image: mysql:5
    container_name: client-legacy
    depends_on:
      - mysql-dev-legacy
    command: mysql -uroot -proot -hmysql-dev-legacy legacyapp
